### ISSUE TITLE
unlimitCoreFileSize doesn't check errno for getrlimit/setrlimit

### ISSUE THREAD

**Issue by kgibm** [eclipse/openj9-omr#35]
While investigating a reported issue of core files not being produced even though supposedly the core hard ulimit was unlimited (waiting on javacore for confirmation), I noticed that [`unlimitCoreFileSize`](https://github.com/eclipse/openj9-omr/blob/v0.15.0-release/port/unix/omrosdump.c#L307) doesn't check the return result (`errno`) for the `getrlimit` and `setrlimit` calls. It would be nice if it did so and printed a warning if those calls failed.

**Comment by andrewcraik** [comment]
@kgibm would you mind reporting this against openj9 directly? this is an openj9 mirror repository used to consume OMR and is not used for issue tracking purposes. I am going to close this here since issue investigation is handled through the main project. Thank you for flagging the issue and we look forward to receiving it on the main project repo.

**Comment by kgibm** [comment]
Sorry about that! Done: https://github.com/eclipse/openj9/issues/6727
